include Makefile.common

all: complete

clean_user:
	
TARI_PATH = ..\addons\libtari
ADDITIONAL_PRELOADS = --preload-file assets

.c.o:
	emcc $< -c -O3 -s USE_SDL=2 -g -s SAFE_HEAP=1 -I$(TARI_PATH)/include -I$(TARI_PATH)\..\..\..\SDL2\lpng1632 -o $@	
	
build_develop: $(OBJS) 
	emcc @Makefile.objs1 -O3 \
	-s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=1 \
	-s USE_SDL=2 -s USE_SDL_IMAGE=2 \
	-s SDL2_IMAGE_FORMATS="[""png""]" \
	-L$(TARI_PATH)/bin -ltari \
	--use-preload-plugins \
    $(ADDITIONAL_PRELOADS) --preload-file $(TARI_PATH)\assets\effects@effects --preload-file $(TARI_PATH)\assets\logo@logo --preload-file $(TARI_PATH)\assets\fonts@fonts --preload-file $(TARI_PATH)\assets\debug@debug -o web\game.html
	-del web\game.html
	-copy $(TARI_PATH)\web\index.html web\index.html

complete: make_folder build_develop

make_folder:
	-mkdir web

clean: clean_user clean_general

clean_general:
	-rmdir /s /q web
	-del *.o

