;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level26:
	dc.l  level26_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 9 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  15  ; boxAmount
	
	; per Box
	
	dc.w  4 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  1 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	
	dc.w  15 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  18 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	
	dc.w  4 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  11  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  11  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  12 ; y pos (16er tile)
	dc.w  12  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  12 ; y pos (16er tile)
	dc.w  14  ; timer value

	
	dc.w  15 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  12  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  13  ; timer value

	dc.w  18 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  15  ; timer value	
	
level26_fieldA:
	INCBIN	"assets/sprites/level26_fieldA.bin"

