;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level32:
 
	dc.l  level32_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 18 ; player start x (16er t)
	dc.w 4 ; player start y (16er t)
 
	dc.w  16  ; boxAmount

	; per Box

	dc.w  17 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  45  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  67  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  64  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  29  ; timer value

	dc.w  14 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  54  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  99  ; timer value

	
	
	
	
	dc.w  17 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  60  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  48 ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  42  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  44  ; timer value

	dc.w  14 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  46  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  42  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	

level32_fieldA:
	INCBIN	"assets/sprites/level32_fieldA.bin"

 