;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level9:
 
	dc.l  level9_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 8 ; player start x (16er t)
	dc.w 2 ; player start y (16er t)
 
	dc.w  8  ; boxAmount
	

	; per Box
	dc.w  7 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  55  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  53  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  38  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  99  ; timer value
	

level9_fieldA:
	INCBIN	"assets\sprites\level9_fieldA.bin"

