;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level33:
 
	dc.l  level33_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 1 ; player start x (16er t)
	dc.w 1 ; player start y (16er t)
 
	dc.w  15  ; boxAmount

	; per Box

	dc.w  2 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  2  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  31  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  31  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  31  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  31  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  31  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  31  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  45  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  99  ; timer value

	dc.w  6 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  88  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  12 ; y pos (16er tile)
	dc.w  88  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  66  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  66  ; timer value

level33_fieldA:
	INCBIN	"assets/sprites/level33_fieldA.bin"

