;;;;;;;;; Generated by MegadriveMapMaker 0.3.4



Level10:
 
	dc.l  level10_fieldA  ; map 	
	
	dc.w 20 ; time gain

	dc.w 15 ; player start x (16er t)
	dc.w 2 ; player start y (16er t)
 
	dc.w  4  ; boxAmount
	
	; per Box
	dc.w  3 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  40  ; timer value
	

	

	
level10_fieldA:
	INCBIN	"assets/sprites/level10_fieldA.bin"

