;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level19:
	dc.l  level19_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 18 ; player start x (16er t)
	dc.w 7 ; player start y (16er t)
 
	dc.w  7  ; boxAmount
	
	; per Box
	dc.w  2 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  50  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  50  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  40  ; timer value
	
	

level19_fieldA:
	INCBIN	"assets/sprites/level19_fieldA.bin"

