;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level8:
 
	dc.l  level8_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 0x9 ; player start x (16er t)
	dc.w 0xB ; player start y (16er t)
 
	dc.w  9  ; boxAmount
	

	; per Box
	dc.w  5 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  56  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  20  ; timer value
	

;; Map Field A (short int)
level8_fieldA:
	INCBIN	"assets\sprites\level8_fieldA.bin"

