;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level15:
 
	dc.l  level15_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 9 ; player start x (16er t)
	dc.w 12 ; player start y (16er t)
 
	dc.w  9  ; boxAmount
	
	; per Box
	dc.w  8 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  55  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  55  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  55  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  11  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  11  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  11  ; timer value




level15_fieldA:
	INCBIN	"assets/sprites/level15_fieldA.bin"

