;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level31:
 
	dc.l  level31_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 9 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  15  ; boxAmount

	; per Box

	dc.w  1 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  7  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  7  ; timer value
	
	dc.w  1 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  4  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  13  ; timer value
	
	dc.w  1 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  16  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  1  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  6  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  6  ; timer value
	

	

level31_fieldA:
	INCBIN	"assets/sprites/level31_fieldA.bin"

