;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level36:
 
	dc.l  level36_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 10 ; player start x (16er t)
	dc.w 8 ; player start y (16er t)
 
	dc.w  11  ; boxAmount

	; per Box

	dc.w  9 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  15  ; timer value

	dc.w  9 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  5  ; timer value

	dc.w  8 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  66  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  66  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  33  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  77  ; timer value
	

level36_fieldA:
	INCBIN	"assets/sprites/level36_fieldA.bin"

