;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level18:
	dc.l  level18_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 1 ; player start x (16er t)
	dc.w 1 ; player start y (16er t)
 
	dc.w  14  ; boxAmount
	
	; per Box
	dc.w  3 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  56  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  67  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  89  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  63  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  38  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  73  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  74  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  93  ; timer value
	
	dc.w  1 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  63  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  46  ; timer value

	dc.w  11 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  58  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  77  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  32  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  99  ; timer value
	

level18_fieldA:
	INCBIN	"assets/sprites/level18_fieldA.bin"

