;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level20:
	dc.l  level20_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 18 ; player start x (16er t)
	dc.w 10 ; player start y (16er t)
 
	dc.w  8  ; boxAmount
	
	; per Box
	dc.w  1 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  20  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value

	dc.w  6 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  40  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	

level20_fieldA:
	INCBIN	"assets/sprites/level20_fieldA.bin"

