;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level3:
 
	dc.l  level3_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 8 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  6  ; boxAmount

	; per Box

	dc.w  7 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  2  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  2  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  4  ; timer value

;; Map Field A (short int)
level3_fieldA:
	INCBIN	"assets\sprites\level3_fieldA.bin"

