 ;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level12:
 
	dc.l  level12_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 7 ; player start x (16er t)
	dc.w 5 ; player start y (16er t)
 
	dc.w  10  ; boxAmount
	
	; per Box
	dc.w  2 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value	
	
	dc.w  2 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  14  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  45  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  27  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  20  ; timer value
	
	
	

level12_fieldA:
	INCBIN	"assets/sprites/level12_fieldA.bin"

