;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level5:
 
	dc.l  level5_fieldA  ; map 	
	
	dc.w 40 ; time gain

	dc.w 0x9 ; player start x (16er t)
	dc.w 0x9 ; player start y (16er t)
 
	dc.w  0x6  ; boxAmount
	

	; per Box
	dc.w  0x10 ; x pos (16er tile)
	dc.w  0x9 ; y pos (16er tile)
	dc.w  30  ; timer value

	dc.w 0x11 ; x pos (16er tile)
	dc.w 0xA ; y pos (16er tile)
	dc.w  20  ; timer value
	
	dc.w 0x11 ; x pos (16er tile)
	dc.w 0x8 ; y pos (16er tile)
	dc.w  15  ; timer value
	
	dc.w 0x11 ; x pos (16er tile)
	dc.w 0x6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w 0xC ; x pos (16er tile)
	dc.w 0x8 ; y pos (16er tile)
	dc.w  6  ; timer value
	
	dc.w  0x8 ; x pos (16er tile)
	dc.w  0x3 ; y pos (16er tile)
	dc.w  15  ; timer value

	
	

level5_fieldA:
	INCBIN	"assets\sprites\level5_fieldA.bin"

