;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level28:
 
	dc.l  level28_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 10 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  16  ; boxAmount

	; per Box
	
	dc.w  9 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  99  ; timer value	
	
	dc.w  15 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  15  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  20  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  25  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  40  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  20  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  40  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  60  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  60  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  60  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  80  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  80  ; timer value

	dc.w  5 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  80  ; timer value
	

level28_fieldA:
	INCBIN	"assets/sprites/level28_fieldA.bin"

