;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level27:
	dc.l  level27_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 8 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  12  ; boxAmount
	
	; per Box
	
	dc.w  11 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  12  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  7  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  2  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  6  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  6  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  12  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  12 ; y pos (16er tile)
	dc.w  13  ; timer value

	
level27_fieldA:
	INCBIN	"assets/sprites/level27_fieldA.bin"

