;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level37:
 
	dc.l  level37_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 10 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  15  ; boxAmount

	; per Box

	dc.w  9 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  8  ; timer value

	
	
	dc.w  1 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  94  ; timer value
	
	dc.w  1 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  56  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  54  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  48  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  38  ; timer value

	dc.w  3 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  59  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  69  ; timer value

	
	
	dc.w  18 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  78  ; timer value
	
	dc.w  18 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  82  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  66  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  77  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  25  ; timer value

	dc.w  16 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  56  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  88  ; timer value

level37_fieldA:
	INCBIN	"assets/sprites/level37_fieldA.bin"

