;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level16:
	dc.l  level16_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 10 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  11  ; boxAmount
	
	; per Box
	dc.w  11 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  19  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  43  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  16  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  32  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  16  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  33  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  24  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  2  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  12  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  30  ; timer value

level16_fieldA:
	INCBIN	"assets/sprites/level16_fieldA.bin"

