;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level13:
 
	dc.l  level13_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 5 ; player start x (16er t)
	dc.w 11 ; player start y (16er t)
 
	dc.w  8  ; boxAmount
	
	; per Box
	dc.w  6 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  15  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  25  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  25  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value


level13_fieldA:
	INCBIN	"assets/sprites/level13_fieldA.bin"

