;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level39:
 
	dc.l  level39_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 8 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  6  ; boxAmount

	; per Box

	dc.w  7 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  2  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  4  ; timer value
	

level39_fieldA:
	INCBIN	"assets/sprites/level39_fieldA.bin"

