;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level35:
 
	dc.l  level35_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 9 ; player start x (16er t)
	dc.w 8 ; player start y (16er t)
 
	dc.w  13  ; boxAmount

	; per Box

	dc.w  9 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  23  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  56  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  34  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  46  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  60  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  15  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  66  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  45  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  46  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  10  ; timer value

	dc.w  14 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  24  ; timer value
	

level35_fieldA:
	INCBIN	"assets/sprites/level35_fieldA.bin"

