;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level14:
 
	dc.l  level14_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 1 ; player start x (16er t)
	dc.w 1 ; player start y (16er t)
 
	dc.w  16  ; boxAmount
	
	; per Box
	dc.w  3 ; x pos (16er tile)
	dc.w  12 ; y pos (16er tile)
	dc.w  66  ; timer value

	dc.w  7 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  14  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  12 ; y pos (16er tile)
	dc.w  23  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  56  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  32  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  36  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  24  ; timer value
	
	dc.w  1 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  22  ; timer value
	
	dc.w  17 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  45  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  12  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  11  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  33  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  43  ; timer value
	
	dc.w  1 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  2  ; timer value
	


level14_fieldA:
	INCBIN	"assets/sprites/level14_fieldA.bin"

