;;;;;;;;; Generated by MegadriveMapMaker 0.3.4



Level6:
 
	dc.l  level6_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 0x9 ; player start x (16er t)
	dc.w 0xC ; player start y (16er t)
 
	dc.w  13  ; boxAmount
	

	; per Box
	dc.w  0x9 ; x pos (16er tile)
	dc.w  0x2 ; y pos (16er tile)
	dc.w  13  ; timer value
	
	dc.w  0x7 ; x pos (16er tile)
	dc.w  0x2 ; y pos (16er tile)
	dc.w  12  ; timer value
	
	dc.w  0xB ; x pos (16er tile)
	dc.w  0x2 ; y pos (16er tile)
	dc.w  11  ; timer value
	
	dc.w  0x8 ; x pos (16er tile)
	dc.w  0x3 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  0xA ; x pos (16er tile)
	dc.w  0x3 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  0x9 ; x pos (16er tile)
	dc.w  0x4 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  0x7 ; x pos (16er tile)
	dc.w  0x4 ; y pos (16er tile)
	dc.w  7  ; timer value
	
	dc.w  0xB ; x pos (16er tile)
	dc.w  0x4 ; y pos (16er tile)
	dc.w  6  ; timer value
	
	dc.w  0x8 ; x pos (16er tile)
	dc.w  0x5 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  0xA ; x pos (16er tile)
	dc.w  0x5 ; y pos (16er tile)
	dc.w  4  ; timer value
	
	dc.w  0x9 ; x pos (16er tile)
	dc.w  0x6 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  0x7 ; x pos (16er tile)
	dc.w  0x6 ; y pos (16er tile)
	dc.w  1  ; timer value
	
	dc.w  0xB ; x pos (16er tile)
	dc.w  0x6 ; y pos (16er tile)
	dc.w  2  ; timer value

	

level6_fieldA:
	INCBIN	"assets\sprites\level6_fieldA.bin"

