;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level25:
	dc.l  level25_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 8 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  10  ; boxAmount
	
	; per Box
	
	dc.w  7 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  1  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  13  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  14  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  13  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  12  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  16  ; timer value


level25_fieldA:
	INCBIN	"assets/sprites/level25_fieldA.bin"

