;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level4:
 
	dc.l  level4_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 0x9 ; player start x (16er t)
	dc.w 0x9 ; player start y (16er t)
 
	dc.w  0x6  ; boxAmount
	

	; per Box
	dc.w  0x9 ; x pos (16er tile)
	dc.w  0x8 ; y pos (16er tile)
	dc.w  99  ; timer value

	dc.w 0xC ; x pos (16er tile)
	dc.w 0x8 ; y pos (16er tile)
	dc.w  6  ; timer value
	
	dc.w 0x6 ; x pos (16er tile)
	dc.w 0x8 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w 0x6 ; x pos (16er tile)
	dc.w 0x5 ; y pos (16er tile)
	dc.w 40  ; timer value
	
	dc.w 0xC ; x pos (16er tile)
	dc.w 0x5 ; y pos (16er tile)
	dc.w  17  ; timer value
	
	dc.w 0x9 ; x pos (16er tile)
	dc.w 0x4 ; y pos (16er tile)
	dc.w  60  ; timer value
	

	



level4_fieldA:
	INCBIN	"assets\sprites\level4_fieldA.bin"

