;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level22:
	dc.l  level22_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 10 ; player start x (16er t)
	dc.w 5 ; player start y (16er t)
 
	dc.w  16  ; boxAmount
	
	; per Box
	
	dc.w  9 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value

	dc.w  16 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  16 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  97  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  97  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  97  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  97  ; timer value

	
level22_fieldA:
	INCBIN	"assets/sprites/level22_fieldA.bin"

