;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level38:
 
	dc.l  level38_fieldA  ; map 	
	
	dc.w 180 ; time gain

	dc.w 10 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  12  ; boxAmount

	; per Box

	dc.w  16 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  66  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  66  ; timer value

	dc.w  7 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  55  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  55  ; timer value

	dc.w  16 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  77  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  77  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  66  ; timer value
	
	dc.w  5 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  44  ; timer value
level38_fieldA:
	INCBIN	"assets/sprites/level38_fieldA.bin"

