;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level7:
 
	dc.l  level7_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 0x1 ; player start x (16er t)
	dc.w 0x1 ; player start y (16er t)
 
	dc.w  ((level7_bend-level7_bstart)/(wsize*3)) ; boxAmount
	

level7_bstart:
	; per Box
	dc.w  0x9 ; x pos (16er tile)
	dc.w  0x8 ; y pos (16er tile)
	dc.w  42  ; timer value
	
	dc.w  0x9 ; x pos (16er tile)
	dc.w  0x6 ; y pos (16er tile)
	dc.w  23  ; timer value
	
	dc.w  0x9 ; x pos (16er tile)
	dc.w  0x5 ; y pos (16er tile)
	dc.w  24  ; timer value

	dc.w  0x9 ; x pos (16er tile)
	dc.w  0x4 ; y pos (16er tile)
	dc.w  27  ; timer value
	
	dc.w  0x9 ; x pos (16er tile)
	dc.w  0x2 ; y pos (16er tile)
	dc.w  5 ; timer value

	dc.w  0x8 ; x pos (16er tile)
	dc.w  0x5 ; y pos (16er tile)
	dc.w  29  ; timer value
	
	dc.w  0x8 ; x pos (16er tile)
	dc.w  0x4 ; y pos (16er tile)
	dc.w  31  ; timer value
	
	dc.w  0xA ; x pos (16er tile)
	dc.w  0x5 ; y pos (16er tile)
	dc.w  23  ; timer value
	
	dc.w  0xA ; x pos (16er tile)
	dc.w  0x4 ; y pos (16er tile)
	dc.w  22  ; timer value

	dc.w  0xB ; x pos (16er tile)
	dc.w  0x4 ; y pos (16er tile)
	dc.w  21  ; timer value
	
	dc.w  0x7 ; x pos (16er tile)
	dc.w  0x4 ; y pos (16er tile)
	dc.w  37  ; timer value
	
	dc.w  0x7 ; x pos (16er tile)
	dc.w  0x3 ; y pos (16er tile)
	dc.w  13  ; timer value
	
	dc.w  0xB ; x pos (16er tile)
	dc.w  0x3 ; y pos (16er tile)
	dc.w  9  ; timer value
level7_bend
	
level7_fieldA:
	INCBIN	"assets\sprites\level7_fieldA.bin"

