;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level24:
	dc.l  level24_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 10 ; player start x (16er t)
	dc.w 2 ; player start y (16er t)
 
	dc.w  15  ; boxAmount
	
	; per Box
	
	dc.w  4 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  20  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  32  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value

	dc.w  15 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  15 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  23  ; timer value
	
level24_fieldA:
	INCBIN	"assets/sprites/level24_fieldA.bin"

