;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level11:
 
	dc.l  level11_fieldA  ; map 	
	
	dc.w 30 ; time gain

	dc.w 3 ; player start x (16er t)
	dc.w 10 ; player start y (16er t)
 
	dc.w  12  ; boxAmount
	
	; per Box
	dc.w  12 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  3  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  99  ; timer value
	


level11_fieldA:
	INCBIN	"assets/sprites/level11_fieldA.bin"

