;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level34:
 
	dc.l  level34_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 1 ; player start x (16er t)
	dc.w 4 ; player start y (16er t)
 
	dc.w  6  ; boxAmount

	; per Box

	dc.w  1 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  7  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  3 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  7  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  4 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  6  ; timer value
	


level34_fieldA:
	INCBIN	"assets/sprites/level34_fieldA.bin"

