;;;;;;;;; Generated by MegadriveMapMaker 0.3.4


Level17:
	dc.l  level17_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 10 ; player start x (16er t)
	dc.w 5 ; player start y (16er t)
 
	dc.w  13  ; boxAmount
	
	; per Box
	dc.w  10 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  23  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  56  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  19  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  27  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  23  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  29  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  21  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  54  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  20  ; timer value
	
	dc.w  14 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  28  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  33  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  17  ; timer value
	

level17_fieldA:
	INCBIN	"assets/sprites/level17_fieldA.bin"

