;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level40:
 
	dc.l  level40_fieldA  ; map 	
	
	dc.w 120 ; time gain

	dc.w 1 ; player start x (16er t)
	dc.w 1 ; player start y (16er t)
 
	dc.w  10  ; boxAmount

	; per Box

	dc.w  2 ; x pos (16er tile)
	dc.w  2 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  1 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  50  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  60  ; timer value
	
	dc.w  2 ; x pos (16er tile)
	dc.w  12 ; y pos (16er tile)
	dc.w  50  ; timer value

	dc.w  12 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  11 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  12 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  12 ; y pos (16er tile)
	dc.w  99  ; timer value

	
level40_fieldA:
	INCBIN	"assets/sprites/level40_fieldA.bin"

