;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level21:
	dc.l  level21_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 10 ; player start x (16er t)
	dc.w 3 ; player start y (16er t)
 
	dc.w  16  ; boxAmount
	
	; per Box
	
	dc.w  9 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  13  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  3 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  4 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  12  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  5 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  7  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  99  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  9 ; y pos (16er tile)
	dc.w  10  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  10 ; y pos (16er tile)
	dc.w  7  ; timer value
	

level21_fieldA:
	INCBIN	"assets/sprites/level21_fieldA.bin"

