;;;;;;;;; Generated by MegadriveMapMaker 0.3.4

Level23:
	dc.l  level23_fieldA  ; map 	
	
	dc.w 129 ; time gain

	dc.w 13 ; player start x (16er t)
	dc.w 6 ; player start y (16er t)
 
	dc.w  11  ; boxAmount
	
	; per Box
	
	dc.w  7 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  2  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  4  ; timer value

	dc.w  11 ; x pos (16er tile)
	dc.w  6 ; y pos (16er tile)
	dc.w  4  ; timer value
	
	dc.w  6 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  9  ; timer value
	
	dc.w  8 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  10 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  5  ; timer value
	
	dc.w  12 ; x pos (16er tile)
	dc.w  7 ; y pos (16er tile)
	dc.w  6  ; timer value
	
	dc.w  7 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  2  ; timer value
	
	dc.w  9 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  6  ; timer value
	
	dc.w  11 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  8  ; timer value
	
	dc.w  13 ; x pos (16er tile)
	dc.w  8 ; y pos (16er tile)
	dc.w  3  ; timer value

	


level23_fieldA:
	INCBIN	"assets/sprites/level23_fieldA.bin"

