#pragma once

#define HANK_MAX_TILES_X (650/50)
#define HANK_MAX_TILES_Y (500/50)

#define HANK_MAX_ENEMY_AMOUNT 6

#define HANK_TILE_SIZE 50
#define HANK_PLATFORM_SIZE_Y	20

#define HANK_ENEMY_RUN_ACCEL 1.3
#define HANK_ENEMY_FRAME_AMOUNT 2

#define HANK_CHARACTER_START_POSITION_X 20
#define HANK_CHARACTER_START_POSITION_Y HANK_PLATFORM_SIZE_Y

#define HANK_CHARACTER_RUN_ACCEL 3
#define HANK_CHARACTER_FRAME_AMOUNT 2

#define HANK_CHARACTER_SIZE_X 50
#define HANK_CHARACTER_SIZE_Y 50

#define HANK_BACKGROUND_POSITION_Z 1
#define HANK_EXIT_POSITION_Z 2
#define HANK_PLATFORM_POSITION_Z 2
#define HANK_CHARACTER_POSITION_Z 4
#define HANK_ENEMY_POSITION_Z 3

// TODO fetch from KOS
#define HANK_SCREEN_SIZE_X	640
#define HANK_SCREEN_SIZE_Y	480

#define HANK_MIDDLE_OF_SCREEN_X	320
#define HANK_MIDDLE_OF_SCREEN_Y	240

#define HANK_GRAVITY 1

#define HANK_PRESS_START_X 212
#define HANK_PRESS_START_Y (480-290)

